// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiWkzfLRG_0APQ08tweDmeARibSYFMbmQ',
    appId: '1:531790754572:web:38dd9a4da32dcdb9dfcf29',
    messagingSenderId: '531790754572',
    projectId: 'pos313-dc017',
    authDomain: 'pos313-dc017.firebaseapp.com',
    storageBucket: 'pos313-dc017.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkPj3W4E4dHTYjsOw_7mPxbDnl77hp7HY',
    appId: '1:531790754572:android:118672935e07de44dfcf29',
    messagingSenderId: '531790754572',
    projectId: 'pos313-dc017',
    storageBucket: 'pos313-dc017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllhl5IgqH8Tmt9hPQyp2nWgTEVnWMSIU',
    appId: '1:531790754572:ios:1bcd130b9751ab3edfcf29',
    messagingSenderId: '531790754572',
    projectId: 'pos313-dc017',
    storageBucket: 'pos313-dc017.firebasestorage.app',
    iosBundleId: 'com.example.miral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiWkzfLRG_0APQ08tweDmeARibSYFMbmQ',
    appId: '1:531790754572:web:404fd77d22d847dddfcf29',
    messagingSenderId: '531790754572',
    projectId: 'pos313-dc017',
    authDomain: 'pos313-dc017.firebaseapp.com',
    storageBucket: 'pos313-dc017.firebasestorage.app',
  );
}
